In [32]:
#Import

from pymatgen.ext.matproj import MPRester
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from jupyter_jsmol import JsmolView

#### On récupère la structure de notre matériaux.

In [33]:
with MPRester ("ozHTdwh3TX0utQzQ") as m:
    #On crée notre stucture sur base du fichier MP
    Structure = m.get_structure_by_material_id("mp-9364")

In [34]:
#Les variables dont on a besoin : 

Conv_Structure = SpacegroupAnalyzer(Structure).get_conventional_standard_structure()

SPanalyzer = SpacegroupAnalyzer(Conv_Structure)

Symm = SPanalyzer.get_symmetry_operations()


 #### On va maintenant étudier les effets de différentes symétries sur les atomes du cristal. Les coordonnées seront données en coordonnées absolues.

## Symétrie 1 : Symétrie de translation sur l'atome de Rb en [0, 0, 0] :

#### Equation : 





In [35]:
print('\n',Symm[12].rotation_matrix,"[0,0,0]","+",Symm[12].translation_vector,"=",Symm[12].operate([0,0,0]))



 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [0,0,0] + [0.66666667 0.33333333 0.33333333] = [0.66666667 0.33333333 0.33333333]


On a donc [2/3, 1/3, 1/3] comme coordonnées d'arrivée. 

#### Illustration :

<img src ="Translation.jpg" style = "width:600px; height:600px"/>


## Symétrie 2 : Rotation l'atome de Sm en [0, 0, 0.5] par rapport a un axe d'ordre 2 :

#### Equation : 





In [36]:
print('\n',Symm[8].rotation_matrix,"[0,0,0.5]","+",Symm[8].translation_vector,"=",Symm[8].operate([0,0,0.5]))


 [[ 1. -1.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]] [0,0,0.5] + [0. 0. 0.] = [ 0.   0.  -0.5]


On a donc [0, 0, -0.5] comme coordonnées d'arrivée. 

#### Illustration :

<img src ="C2 Axis.jpg" style = "width:600px; height:600px"/>


## Symétrie 3 : Plan miroir pour l'atome de S en [0, 1, 0.23] :

#### Equation : 





In [37]:
print('\n',Symm[11].rotation_matrix,"[0,1,0.23]","+",Symm[11].translation_vector,"=",Symm[11].operate([0,1,0.23]))


 [[ 1.  0.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]] [0,1,0.23] + [0. 0. 0.] = [ 0.   -1.    0.23]


On a donc [0, -1, -0.23] comme coordonnées d'arrivée. Ce qu'on peut effectivement observer sur l'illustration qui suit.

#### Illustration :

<img src ="Mirror.jpg" style = "width:600px; height:600px"/>
